### ISSUE TITLE
Github workflow does not render API documentation

### ISSUE THREAD

**Issue by sanghyukmoon** [sanghyukmoon/grid_dendro#2]
When I build and deploy the jupyter book manually by
```
$ PYTHONPATH=./ jupyter-book build docs/
$ ghp-import -n -p -f docs/_build/html
```
then API documentation is rendered without any problem. For example, see https://sanghyukmoon.github.io/grid_dendro/dendrogram.html#

However, when github action does that for me, the API documentation is not rendered. For example, see the jupyter book in Chang-Goo's fork https://changgoo.github.io/grid_dendro/dendrogram.html

**Comment by sanghyukmoon** [comment]
@changgoo Do you have an easy solution for this?

**Comment by changgoo** [comment]
from the workflow log, I see these lines
```
WARNING: autodoc: failed to import module 'boundary' from module 'grid_dendro'; the following exception was raised:
No module named 'numpy'
WARNING: autodoc: failed to import class 'dendrogram.Dendrogram' from module 'grid_dendro'; the following exception was raised:
No module named 'numpy'
WARNING: autodoc: failed to import module 'energy' from module 'grid_dendro'; the following exception was raised:
No module named 'numpy'
```

This means it doesn't have numpy on the runner. The solution is to add `numpy` (and other dependencies if exists) in the `requirements.txt`.

**Comment by sanghyukmoon** [comment]
Thank you so much! Now it is working fine.
